#ifndef DNS_DEBUG_H
#define DNS_DEBUG_H

#include <stdint.h>
#include <stdio.h>
#include <time.h>

#include "../include/DNS_arguments.h"

typedef __uint128_t uint128_t;

#define EVENT_MASK 0xFFFF000000000000
#define INFO_MASK 0x0000FFFFFFFFFFFF

int log_open(void);

void log_close(void);

void log_write(uint64_t payload);

enum log_event {
    LOCAL_SOCKET_FAILED = 1,
    REMOTE_SOCKET_FAILED = 2,
    SOCKET_OPT_FAILED = 3,
    SOCKET_BIND_FAILED = 4,
    SOCKET_INIT_SUCCESS = 5,
    SOCKET_CLOSE_SUCCESS = 6,
    LOCAL_RECEIVE_RECVFROM_FAILED = 7,
    LOCAL_RECEIVE_DECODE_NULL_HEADER = 8,
    LOCAL_RECEIVE_CAN_RESOLVE_LOCALLY = 9,
    LOCAL_RECEIVE_HIT_CACHE = 10,
    LOCAL_RECEIVE_ANS_MALLOC_FAILED = 11,
    LOCAL_RECEIVE_ANS_NAME_MALLOC_FAILED = 12,
    LOCAL_RECEIVE_REPLY_SIZE_ERROR = 13,
    LOCAL_RECEIVE_DNS_MESSAGE_FREE_SUCCESS = 14,
    LOCAL_RECEIVE_CANNOT_HIT_CACHE = 15,
    LOCAL_RECEIVE_NO_EMPTY_SLOT_DROP = 16,
    LOCAL_RECEIVE_SENT_TO_UPSTREAM = 17,
    REMOTE_RECEIVE_MSG_SIZE_ERR = 18,
    REMOTE_RECEIVE_NO_ORIG_ID_DROP = 19,
    REMOTE_RECEIVE_SENT_TO_CLIENT = 20,
    REMOTE_RECEIVE_NO_GLOBAL_CACHE = 21,
    REMOTE_RECEIVE_HAS_GLOBAL_CACHE = 22,
    REMOTE_RECEIVE_CACHED_ANSWER_SUCCESS = 23,
    BLOCK_MODE_START = 24,
    BLOCK_MODE_ERRNO_EINTR = 25,
    BLOCK_MODE_ERRNO_SELECT = 72,
    BLOCK_MODE_TIMEOUT = 26,
    BLOCK_MODE_LOCAL_RECEIVE = 27,
    BLOCK_MODE_REMOTE_RECEIVE = 28,
    NON_BLOCK_MODE_START = 29,
    NON_BLOCK_MODE_LOCAL_FGETFL_ERR = 30,
    NON_BLOCK_MODE_LOCAL_FSETFL_ERR = 31,
    NON_BLOCK_MODE_REMOTE_FGETFL_ERR = 32,
    NON_BLOCK_MODE_REMOTE_FSETFL_ERR = 33,
    NON_BLOCK_MODE_LOCAL_RECEIVE = 73,
    NON_BLOCK_MODE_REMOTE_RECEIVE = 74,
    NON_BLOCK_SWEEP = 34,
    CACHE_FIND = 35,
    CACHE_CLEAR = 36,
    CACHE_ERASE = 37,
    CACHE_INSERT = 38,
    CACHE_DESTROY = 39,
    CACHE_INIT = 40,
    CREATE_HSET_ERR = 41,
    CREATE_HSET_SUCCESS = 42,
    CONVERT_READ_BYTE_ERR = 43,
    CONVERT_WRITE_BYTE = 44,
    GET_DNS_HEADER_SUCCESS = 45,
    GET_DNS_QUESTION_MALLOC_ERR = 46,
    GET_DNS_QUESTION_SUCCESS = 47,
    GET_DNS_DOMAIN_SUCCESS = 48,
    GET_DNS_ANSWER_NULL_PTR_ERR = 49,
    GET_DNS_ANSWER_NOT_SUPPORTED_TYPE_ERR = 50,
    DNS_MESSAGE_DECODE_SUCCESS = 51,
    SET_DNS_HEADER_SUCCESS = 52,
    SET_DNS_DOMAIN_SUCCESS = 53,
    SET_DNS_QUESTION_SUCCESS = 54,
    SET_DNS_ANSWER_SUCCESS = 55,
    DNS_MESSAGE_ENCODE_SUCCESS = 56,
    DNS_MESSAGE_FREE_SUCCESS = 57,
    ID_MAP_INIT = 58,
    ID_MAP_INSERT_ARGS_NULL_PTR_ERR = 59,
    ID_MAP_INSERT_FULL_TABLE_ERR = 60,
    ID_MAP_FIND_ID_OUT_BOUND_ERR = 61,
    ID_MAP_FIND_USED_ID_ERR = 62,
    ID_MAP_FIND_TIMEOUT_ERR = 63,
    ID_MAP_FIND_SUCCESS = 64,
    ID_MAP_ERASE_ID_OUT_BOUND_ERR = 65,
    ID_MAP_ERASE_ID_MAP_USED_ERR = 66,
    ID_MAP_ERASED_SUCCESS = 67,
    ID_MAP_SWEEP_TIMEOUT_SUCCESS = 68,
    UI8_PTR_STACK_INIT = 69,
    UI8_PTR_STACK_PUSH = 70,
    UI8_PTR_STACK_POP = 71
};

typedef enum log_event log_event_t;

#endif